### ISSUE TITLE
CustomType integration test fails in CCI

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/enigma-go#242]
After the merge of #241 the integration test for custom types started failing in CCI. It does not seem to be related to the change itself since the test also fails when reverting the commit.

https://app.circleci.com/pipelines/github/qlik-oss/enigma-go/330/workflows/b1540f06-1718-4b20-9ce0-070f5e9f8c0f/jobs/2056

```
#!/bin/bash -eo pipefail
./examples/run_examples.sh


Starting example: basics/custom-type/custom-type.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x74453c]

goroutine 1 [running]:
github.com/qlik-oss/enigma-go/v3.(*Doc).CreateSessionObjectRaw(0x0, 0x850d10, 0xc00001c058, 0x7699e0, 0xc00052e000, 0x20, 0x796e60, 0x1)
	/home/circleci/project/qix_generated.go:6340 +0x7c
main.(*customDoc).CreateCustomObject(0xc00028fed8, 0x850d10, 0xc00001c058, 0xc00052e000, 0x84c6a0, 0xc000594168, 0x0)
	/home/circleci/project/examples/basics/custom-type/custom-type.go:78 +0x5c
main.main()
	/home/circleci/project/examples/basics/custom-type/custom-type.go:60 +0x554
exit status 2

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by wennmo** [comment]
Expired token used in CCI, it has now been replaced.
